import { useState } from "react";
import title from "../Images/title.png";
import LaunchCarousel from "./LaunchCarousel";
import LaunchPad from "./LaunchPad";
import LaunchDescription from "./LaunchDescription";
import horizon from "../Images/horizon.png";

function Home() {
  const [index, setIndex] = useState(0);

  const handleSelect = (selectedIndex, e) => {
    setIndex(selectedIndex);
  };

  const futureLaunches = {
    valid_auth: true,
    count: 25,
    limit: 25,
    total: 117,
    last_page: 5,
    result: [
      {
        id: 3187,
        cospar_id: "",
        sort_date: "1661924400",
        name: "Starlink-58 (3-4)",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 1,
          name: "SLC-4E",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [{ id: 4912, name: "Starlink-58 (3-4)", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Starlink-58 (3-4) mission on Wednesday, August 31, 2022 at 5:40 AM (UTC).",
        win_open: "2022-08-31T05:40Z",
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: null, quarter: null },
        date_str: "Aug 31",
        tags: [
          { id: 103, text: "B1063" },
          { id: 92, text: "Series: SpaceX Starlink" },
        ],
        slug: "starlink-3-4",
        weather_summary: "Partly Cloudy\nTemp: 56.15F\nWind: 12.8mph\n",
        weather_temp: 56.15,
        weather_condition: "Partly Cloudy",
        weather_wind_mph: 12.8,
        weather_icon: "wi-night-alt-cloudy",
        weather_updated: "2022-08-29T12:00:36+00:00",
        quicktext:
          "Falcon 9 - Starlink-58 (3-4) - Wed Aug 31, 2022 05:40:00 UTC (L-1 days, 09:19:05) - https://rocketlaunch.live/launch/starlink-3-4 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-25T20:23:42+00:00",
      },
      {
        id: 3189,
        cospar_id: "",
        sort_date: "1662337920",
        name: "Starlink-59 (4-20)",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 3,
          name: "SLC-40",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [
          { id: 4914, name: "Starlink-59 (4-20)", description: null },
          { id: 4915, name: "Sherpa-LTC2", description: null },
        ],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Starlink-59 (4-20) mission on Monday, September 5, 2022 at 12:32 AM (UTC).",
        win_open: "2022-09-05T00:32Z",
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: null, quarter: null },
        date_str: "Sep 05",
        tags: [{ id: 92, text: "Series: SpaceX Starlink" }],
        slug: "starlink-4-20",
        weather_summary: "Humid\nTemp: 86.5F\nWind: 9.32mph\n",
        weather_temp: 86.5,
        weather_condition: "Humid",
        weather_wind_mph: 9.32,
        weather_icon: "wi-night-clear",
        weather_updated: "2022-08-29T12:00:38+00:00",
        quicktext:
          "Falcon 9 - Starlink-59 (4-20) - Mon Sep 05, 2022 00:32:00 UTC (L-6 days, 04:11:05) - https://rocketlaunch.live/launch/starlink-4-20 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-23T13:31:42+00:00",
      },
      {
        id: 38,
        cospar_id: "",
        sort_date: "1662422396",
        name: "Artemis I (EM-1)",
        provider: { id: 2, name: "NASA", slug: "nasa" },
        vehicle: { id: 15, name: "SLS", company_id: 2, slug: "sls" },
        pad: {
          id: 36,
          name: "LC-39B",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [
          {
            id: 35,
            name: "Artemis I (EM-1)",
            description:
              "On its debut flight, the Space Launch System (SLS) will send an uncrewed Orion Multi-Purpose Crew Vehicle on a four to six-week mission to the Moon and back, including 6 days in a retrograde lunar orbit.",
          },
        ],
        mission_description:
          "On its debut flight, the Space Launch System (SLS) will send an uncrewed Orion Multi-Purpose Crew Vehicle on a four to six-week mission to the Moon and back, including 6 days in a retrograde lunar orbit.",
        launch_description:
          "A NASA SLS rocket will launch the Artemis I (EM-1) mission. The launch date is currently targeted for September 05, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 5, year: 2022, quarter: null },
        date_str: "Sep 05",
        tags: [
          { id: 48, text: "Lunar Orbit" },
          { id: 91, text: "Series: NASA Artemis" },
          { id: 23, text: "Test Flight" },
          { id: 21, text: "Uncrewed" },
          { id: 14, text: "Vehicle Debut" },
        ],
        slug: "em-1",
        weather_summary:
          "Humid and Mostly Cloudy\nTemp: 78.9F\nWind: 4.43mph\n",
        weather_temp: 78.9,
        weather_condition: "Humid and Mostly Cloudy",
        weather_wind_mph: 4.43,
        weather_icon: "wi-day-cloudy",
        weather_updated: "2022-08-29T12:00:36+00:00",
        quicktext:
          "SLS - Artemis I (EM-1) - Sep 05 (estimated) - https://rocketlaunch.live/launch/em-1 for info/stream",
        media: [
          {
            id: 1079,
            media_url: "",
            youtube_vidid: "CMLD0Lp0JBg",
            featured: true,
            ldfeatured: true,
            approved: true,
          },
          {
            id: 1083,
            media_url: "",
            youtube_vidid: "Y9x-QkWCzrc",
            featured: true,
            ldfeatured: true,
            approved: true,
          },
          {
            id: 1082,
            media_url: "",
            youtube_vidid: "0_vyZiVxEEo",
            featured: true,
            ldfeatured: true,
            approved: true,
          },
        ],
        result: -1,
        suborbital: false,
        modified: "2022-08-29T14:25:29+00:00",
      },
      {
        id: 2699,
        cospar_id: "",
        sort_date: "1662508796",
        name: "RS1 Flight 1",
        provider: { id: 142, name: "ABL Space", slug: "abl-space" },
        vehicle: { id: 121, name: "RS1", company_id: 142, slug: "rs1" },
        pad: {
          id: 126,
          name: "LP-3C",
          location: {
            id: 47,
            name: "Pacific Spaceport Complex - Alaska",
            state: "AK",
            statename: "Alaska",
            country: "United States",
            slug: "pacific-spaceport-co",
          },
        },
        missions: [{ id: 4199, name: "RS1 Flight 1", description: null }],
        mission_description: null,
        launch_description:
          "An ABL Space RS1 rocket will launch the RS1 Flight 1 mission. The launch date is currently targeted for September 06, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 6, year: 2022, quarter: null },
        date_str: "Sep 06",
        tags: [
          { id: 23, text: "Test Flight" },
          { id: 14, text: "Vehicle Debut" },
        ],
        slug: "rs1-flight-1",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "RS1 - RS1 Flight 1 - Sep 06 (estimated) - https://rocketlaunch.live/launch/rs1-flight-1 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-19T14:47:11+00:00",
      },
      {
        id: 3190,
        cospar_id: "",
        sort_date: "1662508796",
        name: "Eutelsat Konnect VHTS",
        provider: { id: 4, name: "Arianespace", slug: "arianespace" },
        vehicle: { id: 2, name: "Ariane 5", company_id: 5, slug: "ariane-5" },
        pad: {
          id: 17,
          name: "ELA-3",
          location: {
            id: 70,
            name: "Guiana Space Centre",
            state: null,
            statename: null,
            country: "French Guiana",
            slug: "guiana-space-centre",
          },
        },
        missions: [
          { id: 4916, name: "Eutelsat Konnect VHTS", description: null },
        ],
        mission_description: null,
        launch_description:
          "An Arianespace Ariane 5 rocket will launch the Eutelsat Konnect VHTS mission. The launch date is currently targeted for September 06, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 6, year: 2022, quarter: null },
        date_str: "Sep 06",
        tags: [],
        slug: "eutelsat-konnect-vht",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Ariane 5 - Eutelsat Konnect VHTS - Sep 06 (estimated) - https://rocketlaunch.live/launch/eutelsat-konnect-vht for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-16T12:56:57+00:00",
      },
      {
        id: 3191,
        cospar_id: "",
        sort_date: "1662595196",
        name: "Starlink (4-2)",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 2,
          name: "LC-39A",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [
          { id: 4917, name: "Starlink (4-2)", description: null },
          { id: 4918, name: "BlueWalker-3", description: null },
        ],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Starlink (4-2) mission. The launch date is currently targeted for September 07, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 7, year: 2022, quarter: null },
        date_str: "Sep 07",
        tags: [{ id: 92, text: "Series: SpaceX Starlink" }],
        slug: "starlink-4-2",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - Starlink (4-2) - Sep 07 (estimated) - https://rocketlaunch.live/launch/starlink-4-2 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-19T14:47:58+00:00",
      },
      {
        id: 2967,
        cospar_id: "",
        sort_date: "1662933600",
        name: '"To the Black"',
        provider: { id: 91, name: "Firefly", slug: "firefly" },
        vehicle: { id: 58, name: "Alpha", company_id: 91, slug: "alpha" },
        pad: {
          id: 38,
          name: "SLC-2W",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [{ id: 4606, name: "Alpha Flight 2", description: null }],
        mission_description: null,
        launch_description:
          'A Firefly Alpha rocket will launch the "To the Black" mission on Sunday, September 11, 2022 at 10:00 PM (UTC).',
        win_open: "2022-09-11T22:00Z",
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: null, quarter: null },
        date_str: "Sep 11",
        tags: [{ id: 23, text: "Test Flight" }],
        slug: "alpha-flight-2",
        weather_summary: "Partly Cloudy\nTemp: 64.73F\nWind: 14.39mph\n",
        weather_temp: 64.73,
        weather_condition: "Partly Cloudy",
        weather_wind_mph: 14.39,
        weather_icon: "wi-day-cloudy",
        weather_updated: "2022-08-29T12:00:38+00:00",
        quicktext:
          'Alpha - "To the Black" - Sun Sep 11, 2022 22:00:00 UTC (L-13 days, 01:39:05) - https://rocketlaunch.live/launch/alpha-flight-2 for info/stream',
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-22T15:12:58+00:00",
      },
      {
        id: 2752,
        cospar_id: "",
        sort_date: "1663804796",
        name: "Soyuz MS-22",
        provider: { id: 13, name: "Roscosmos", slug: "roscosmos" },
        vehicle: { id: 20, name: "Soyuz-2", company_id: 13, slug: "soyuz-2" },
        pad: {
          id: 28,
          name: "LC-31/6",
          location: {
            id: 50,
            name: "Baikonur Cosmodrome",
            state: null,
            statename: null,
            country: "Kazakhstan",
            slug: "baikonur-cosmodrome",
          },
        },
        missions: [{ id: 4255, name: "Soyuz MS-22", description: null }],
        mission_description: null,
        launch_description:
          "A Roscosmos Soyuz-2 rocket will launch the Soyuz MS-22 mission. The launch date is currently targeted for September 21, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 21, year: 2022, quarter: null },
        date_str: "Sep 21",
        tags: [
          { id: 9, text: "Crewed" },
          { id: 17, text: "ISS Expedition" },
        ],
        slug: "soyuz-ms-22",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Soyuz-2 - Soyuz MS-22 - Sep 21 (estimated) - https://rocketlaunch.live/launch/soyuz-ms-22 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-01-06T03:49:03+00:00",
      },
      {
        id: 221,
        cospar_id: "",
        sort_date: "1664063996",
        name: "NROL-91",
        provider: {
          id: 3,
          name: "United Launch Alliance (ULA)",
          slug: "united-launch-alliance-ula",
        },
        vehicle: {
          id: 26,
          name: "Delta IV Heavy",
          company_id: 3,
          slug: "delta-iv-heavy",
        },
        pad: {
          id: 14,
          name: "SLC-6",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [{ id: 213, name: "NROL-91", description: null }],
        mission_description: null,
        launch_description:
          "A United Launch Alliance (ULA) Delta IV Heavy rocket will launch the NROL-91 mission. The launch date is currently targeted for September 24, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 24, year: 2022, quarter: null },
        date_str: "Sep 24",
        tags: [{ id: 8, text: "Classified Payload" }],
        slug: "nrol-91",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Delta IV Heavy - NROL-91 - Sep 24 (estimated) - https://rocketlaunch.live/launch/nrol-91 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-24T20:56:24+00:00",
      },
      {
        id: 228,
        cospar_id: "",
        sort_date: "1664582397",
        name: "Oceansat-3 (EOS-6)",
        provider: { id: 18, name: "ISRO", slug: "isro" },
        vehicle: { id: 21, name: "PSLV", company_id: 18, slug: "pslv" },
        pad: {
          id: 7,
          name: "FLP",
          location: {
            id: 67,
            name: "Satish Dhawan Space Centre",
            state: null,
            statename: null,
            country: "India",
            slug: "satish-dhawan-space-",
          },
        },
        missions: [{ id: 220, name: "Oceansat-3 (EOS-6)", description: null }],
        mission_description: null,
        launch_description:
          "An ISRO PSLV rocket will launch the Oceansat-3 (EOS-6) mission. The launch date is currently targeted for September, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: null, year: 2022, quarter: null },
        date_str: "Sep 2022",
        tags: [{ id: 25, text: "Earth Observation Satellite" }],
        slug: "oceansat-3",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "PSLV - Oceansat-3 (EOS-6) - Sep 2022 (estimated) - https://rocketlaunch.live/launch/oceansat-3 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T17:45:44+00:00",
      },
      {
        id: 2969,
        cospar_id: "",
        sort_date: "1664582397",
        name: "SES-20 & SES-21",
        provider: {
          id: 3,
          name: "United Launch Alliance (ULA)",
          slug: "united-launch-alliance-ula",
        },
        vehicle: { id: 3, name: "Atlas V", company_id: 3, slug: "atlas-v" },
        pad: {
          id: 4,
          name: "SLC-41",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [{ id: 4608, name: "SES-20 & SES-21", description: null }],
        mission_description: null,
        launch_description:
          "A United Launch Alliance (ULA) Atlas V rocket will launch the SES-20 & SES-21 mission. The launch date is currently targeted for September, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: null, year: 2022, quarter: null },
        date_str: "Sep 2022",
        tags: [],
        slug: "ses-20-ses-21",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Atlas V - SES-20 & SES-21 - Sep 2022 (estimated) - https://rocketlaunch.live/launch/ses-20-ses-21 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-22T12:23:25+00:00",
      },
      {
        id: 3188,
        cospar_id: "",
        sort_date: "1664582397",
        name: '"The Owl Spreads Its Wings"',
        provider: { id: 26, name: "Rocket Lab", slug: "rocket-lab" },
        vehicle: { id: 18, name: "Electron", company_id: 26, slug: "electron" },
        pad: {
          id: 19,
          name: "LC-1A",
          location: {
            id: 20,
            name: "Rocket Lab Launch Complex, Mahia Peninsula",
            state: null,
            statename: null,
            country: "New Zealand",
            slug: "rocket-lab-launch-co",
          },
        },
        missions: [{ id: 4913, name: "StriX-1", description: null }],
        mission_description: null,
        launch_description:
          'A Rocket Lab Electron rocket will launch the "The Owl Spreads Its Wings" mission. The launch date is currently targeted for September, 2022 (UTC).',
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: null, year: 2022, quarter: null },
        date_str: "Sep 2022",
        tags: [],
        slug: "strix-1",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          'Electron - "The Owl Spreads Its Wings" - Sep 2022 (estimated) - https://rocketlaunch.live/launch/strix-1 for info/stream',
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-15T20:52:21+00:00",
      },
      {
        id: 1181,
        cospar_id: "",
        sort_date: "1664582398",
        name: '"Good Luck, Have Fun"',
        provider: {
          id: 127,
          name: "Relativity Space",
          slug: "relativity-space",
        },
        vehicle: {
          id: 92,
          name: "Terran 1",
          company_id: 127,
          slug: "terran-1",
        },
        pad: {
          id: 128,
          name: "SLC-16",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [{ id: 1261, name: "Terran 1 Flight 1", description: null }],
        mission_description: null,
        launch_description:
          'A Relativity Space Terran 1 rocket will launch the "Good Luck, Have Fun" mission. The launch date is currently targeted for Q3 2022 (UTC).',
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: 2022, quarter: 3 },
        date_str: "Q3 2022",
        tags: [
          { id: 23, text: "Test Flight" },
          { id: 14, text: "Vehicle Debut" },
        ],
        slug: "terran-1-flight-1",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          'Terran 1 - "Good Luck, Have Fun" - Q3 2022 (estimated) - https://rocketlaunch.live/launch/terran-1-flight-1 for info/stream',
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T17:42:46+00:00",
      },
      {
        id: 2659,
        cospar_id: "",
        sort_date: "1664582398",
        name: "Full Stack Test Flight",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: {
          id: 119,
          name: "Super Heavy / Starship Prototype",
          company_id: 1,
          slug: "super-heavy-starship-prototype",
        },
        pad: {
          id: 114,
          name: "Launch Pad",
          location: {
            id: 89,
            name: "Boca Chica Launch Site",
            state: "TX",
            statename: "Texas",
            country: "United States",
            slug: "boca-chica-launch-si",
          },
        },
        missions: [
          {
            id: 4137,
            name: "Full Stack Test Flight",
            description:
              "As this is a test program, any dates and times are simply an estimate based on publicly known information.",
          },
        ],
        mission_description:
          "As this is a test program, any dates and times are simply an estimate based on publicly known information.",
        launch_description:
          "A SpaceX Super Heavy / Starship Prototype rocket will launch the Full Stack Test Flight mission. The launch date is currently targeted for Q3 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: 2022, quarter: 3 },
        date_str: "Q3 2022",
        tags: [{ id: 23, text: "Test Flight" }],
        slug: "full-stack-test-flig",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Super Heavy / Starship Prototype - Full Stack Test Flight - Q3 2022 (estimated) - https://rocketlaunch.live/launch/full-stack-test-flig for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-06-28T14:22:34+00:00",
      },
      {
        id: 3108,
        cospar_id: "",
        sort_date: "1664841596",
        name: "Crew-5",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 2,
          name: "LC-39A",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [{ id: 4803, name: "Crew-5", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Crew-5 mission. The launch date is currently targeted for October 03, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: 3, year: 2022, quarter: null },
        date_str: "Oct 03",
        tags: [
          { id: 9, text: "Crewed" },
          { id: 22, text: "NASA Commercial Crew Program (CCP)" },
        ],
        slug: "crew-5",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - Crew-5 - Oct 03 (estimated) - https://rocketlaunch.live/launch/crew-5 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-26T02:22:42+00:00",
      },
      {
        id: 2822,
        cospar_id: "",
        sort_date: "1665878396",
        name: "CRS2 NG-18 (Cygnus)",
        provider: {
          id: 88,
          name: "Northrop Grumman",
          slug: "northrop-grumman",
        },
        vehicle: { id: 5, name: "Antares", company_id: 88, slug: "antares" },
        pad: {
          id: 6,
          name: "Pad 0A",
          location: {
            id: 66,
            name: "Mid-Atlantic Regional Spaceport (Wallops Island)",
            state: "VA",
            statename: "Virginia",
            country: "United States",
            slug: "mid-atlantic-regiona",
          },
        },
        missions: [
          { id: 4385, name: "CRS2 NG-18 (Cygnus)", description: null },
        ],
        mission_description: null,
        launch_description:
          "A Northrop Grumman Antares rocket will launch the CRS2 NG-18 (Cygnus) mission. The launch date is currently targeted for October 15, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: 15, year: 2022, quarter: null },
        date_str: "Oct 15",
        tags: [{ id: 12, text: "ISS Cargo" }],
        slug: "crs2-ng-18",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Antares - CRS2 NG-18 (Cygnus) - Oct 15 (estimated) - https://rocketlaunch.live/launch/crs2-ng-18 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-07-30T12:00:52+00:00",
      },
      {
        id: 514,
        cospar_id: "",
        sort_date: "1667260797",
        name: "O3b mPower-1",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 56,
          name: "Pad TBD",
          location: {
            id: 52,
            name: "Cape Canaveral / KSC TBD",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-ksc-t",
          },
        },
        missions: [{ id: 512, name: "O3b mPower-1", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the O3b mPower-1 mission. The launch date is currently targeted for October, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: null, year: 2022, quarter: null },
        date_str: "Oct 2022",
        tags: [{ id: 24, text: "Communications Satellite" }],
        slug: "o3b-mpower-1",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - O3b mPower-1 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/o3b-mpower-1 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T17:44:00+00:00",
      },
      {
        id: 515,
        cospar_id: "",
        sort_date: "1667260797",
        name: "O3b mPower-2",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 56,
          name: "Pad TBD",
          location: {
            id: 52,
            name: "Cape Canaveral / KSC TBD",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-ksc-t",
          },
        },
        missions: [{ id: 513, name: "O3b mPower-2", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the O3b mPower-2 mission. The launch date is currently targeted for October, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: null, year: 2022, quarter: null },
        date_str: "Oct 2022",
        tags: [{ id: 24, text: "Communications Satellite" }],
        slug: "o3b-mpower-2",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - O3b mPower-2 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/o3b-mpower-2 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T17:44:17+00:00",
      },
      {
        id: 2970,
        cospar_id: "",
        sort_date: "1667260797",
        name: "SES-18 & SES-19",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 56,
          name: "Pad TBD",
          location: {
            id: 52,
            name: "Cape Canaveral / KSC TBD",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-ksc-t",
          },
        },
        missions: [{ id: 4609, name: "SES-18 & SES-19", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the SES-18 & SES-19 mission. The launch date is currently targeted for October, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: null, year: 2022, quarter: null },
        date_str: "Oct 2022",
        tags: [],
        slug: "ses-18-ses-19",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - SES-18 & SES-19 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/ses-18-ses-19 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-05-28T15:34:21+00:00",
      },
      {
        id: 323,
        cospar_id: "",
        sort_date: "1667347196",
        name: "JPSS-2",
        provider: {
          id: 3,
          name: "United Launch Alliance (ULA)",
          slug: "united-launch-alliance-ula",
        },
        vehicle: { id: 3, name: "Atlas V", company_id: 3, slug: "atlas-v" },
        pad: {
          id: 22,
          name: "SLC-3E",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [
          { id: 309, name: "JPSS-2", description: null },
          { id: 4188, name: "LOFTID", description: null },
        ],
        mission_description: null,
        launch_description:
          "A United Launch Alliance (ULA) Atlas V rocket will launch the JPSS-2 mission. The launch date is currently targeted for November 01, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 11, day: 1, year: 2022, quarter: null },
        date_str: "Nov 01",
        tags: [
          { id: 25, text: "Earth Observation Satellite" },
          { id: 29, text: "Polar Orbit" },
        ],
        slug: "jpss-2",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Atlas V - JPSS-2 - Nov 01 (estimated) - https://rocketlaunch.live/launch/jpss-2 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T20:14:20+00:00",
      },
      {
        id: 3172,
        cospar_id: "",
        sort_date: "1667865596",
        name: "Transporter-6",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 3,
          name: "SLC-40",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [{ id: 4898, name: "Transporter-6", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Transporter-6 mission. The launch date is currently targeted for November 07, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 11, day: 7, year: 2022, quarter: null },
        date_str: "Nov 07",
        tags: [],
        slug: "transporter-6",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - Transporter-6 - Nov 07 (estimated) - https://rocketlaunch.live/launch/transporter-6 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-19T17:33:55+00:00",
      },
      {
        id: 1208,
        cospar_id: "",
        sort_date: "1669852797",
        name: "USSF-67",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: {
          id: 7,
          name: "Falcon Heavy",
          company_id: 1,
          slug: "falcon-heavy",
        },
        pad: {
          id: 2,
          name: "LC-39A",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [{ id: 1288, name: "USSF-67", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon Heavy rocket will launch the USSF-67 mission. The launch date is currently targeted for November, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 11, day: null, year: 2022, quarter: null },
        date_str: "Nov 2022",
        tags: [],
        slug: "ussf-67",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon Heavy - USSF-67 - Nov 2022 (estimated) - https://rocketlaunch.live/launch/ussf-67 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T20:16:57+00:00",
      },
      {
        id: 404,
        cospar_id: "",
        sort_date: "1670284796",
        name: "SWOT",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 1,
          name: "SLC-4E",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [{ id: 392, name: "SWOT", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the SWOT mission. The launch date is currently targeted for December 05, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 12, day: 5, year: 2022, quarter: null },
        date_str: "Dec 05",
        tags: [{ id: 25, text: "Earth Observation Satellite" }],
        slug: "swot",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - SWOT - Dec 05 (estimated) - https://rocketlaunch.live/launch/swot for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-26T16:41:41+00:00",
      },
      {
        id: 465,
        cospar_id: "",
        sort_date: "1672531197",
        name: "USSF-44",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: {
          id: 7,
          name: "Falcon Heavy",
          company_id: 1,
          slug: "falcon-heavy",
        },
        pad: {
          id: 2,
          name: "LC-39A",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [{ id: 448, name: "USSF-44", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon Heavy rocket will launch the USSF-44 mission. The launch date is currently targeted for December, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 12, day: null, year: 2022, quarter: null },
        date_str: "Dec 2022",
        tags: [],
        slug: "afspc-44",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon Heavy - USSF-44 - Dec 2022 (estimated) - https://rocketlaunch.live/launch/afspc-44 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-06-28T14:21:13+00:00",
      },
      {
        id: 600,
        cospar_id: null,
        sort_date: "1672531197",
        name: "PACE",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 3,
          name: "SLC-40",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [{ id: 626, name: "PACE", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the PACE mission. The launch date is currently targeted for December, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 12, day: null, year: 2022, quarter: null },
        date_str: "Dec 2022",
        tags: [],
        slug: "pace",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - PACE - Dec 2022 (estimated) - https://rocketlaunch.live/launch/pace for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2020-02-04T22:48:59+00:00",
      },
    ],
  };

  /* 
  name: The name of the launch, generally derived from the primary mission's name

  provider: An object with launch provider information

  vehicle: An object with launch vehicle information

  pad: An object with launch pad information
    pad.location.name: A string with the launch pad location
    pad.name: A string with the specific launch pad id
    pad.location.state: A string with the state the launch is in

  missions: An array of objects with mission information
    missions.name: name of the mission
  launch_description: bare bones details of the launch
  mission_description: more in-depth description of the mission (sometimes null)
  win_open: time the launch window opens
  weather_summary: the weather for the launch window
  media[0].youtube_vidid: the id of the youtube video?
  */

  // launch info (company, mission, date, etc)
  // pad info
  // weather
  // media if there

  return (
    <>
      <div id="home_title_container">
        {/* <p style={{ textAlign: "center", fontSize: 72 }}>flight horizons</p> */}
        <img id="home_title" src={title} alt="flight_horizons" />
      </div>

      <div id="launch_container">
        <LaunchPad futureLaunches={futureLaunches.result} index={index} />
        
        <LaunchCarousel
          futureLaunches={futureLaunches.result}
          handleSelect={handleSelect}
        />

        <LaunchDescription
          futureLaunches={futureLaunches.result}
          index={index}
        />
      </div>

      <div id="filler_container"></div>

      <div id="horizon_container">
        <img id="horizon_image" src={horizon} alt="image_of_horizon" />
      </div>
    </>
  );
}

export default Home;
