import title from "../Images/title.png";
import UpcomingLaunches from "./UpcomingLaunches";
import horizon from "../Images/horizon.png";

function Home() {

  const futureLaunches = {
    valid_auth: true,
    count: 25,
    limit: 25,
    total: 119,
    last_page: 5,
    result: [
      {
        id: 3185,
        cospar_id: "",
        sort_date: "1660937040",
        name: "Starlink-56 (4-27)",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 3,
          name: "SLC-40",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [{ id: 4910, name: "Starlink-56 (4-27)", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Starlink-56 (4-27) mission on Friday, August 19, 2022 at 7:24 PM (UTC).",
        win_open: "2022-08-19T19:24Z",
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: null, quarter: null },
        date_str: "Aug 19",
        tags: [
          { id: 105, text: "B1062" },
          { id: 92, text: "Series: SpaceX Starlink" },
        ],
        slug: "starlink-56-4-27",
        weather_summary:
          "Humid and Partly Cloudy\nTemp: 89.29F\nWind: 8.27mph\n",
        weather_temp: 89.29,
        weather_condition: "Humid and Partly Cloudy",
        weather_wind_mph: 8.27,
        weather_icon: "wi-day-cloudy",
        weather_updated: "2022-08-18T12:00:22+00:00",
        quicktext:
          "Falcon 9 - Starlink-56 (4-27) - Fri Aug 19, 2022 19:24:00 UTC (L-20:53:25) - https://rocketlaunch.live/launch/starlink-56-4-27 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-15T14:17:26+00:00",
      },
      {
        id: 3186,
        cospar_id: "",
        sort_date: "1661651520",
        name: "Starlink-57 (4-23)",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 2,
          name: "LC-39A",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [{ id: 4911, name: "Starlink-57 (4-23)", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Starlink-57 (4-23) mission on Sunday, August 28, 2022 at 1:52 AM (UTC).",
        win_open: "2022-08-28T01:52Z",
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: null, quarter: null },
        date_str: "Aug 28",
        tags: [
          { id: 109, text: "B1067" },
          { id: 92, text: "Series: SpaceX Starlink" },
        ],
        slug: "starlink-4-23",
        weather_summary:
          "Humid and Mostly Cloudy\nTemp: 82.33F\nWind: 7.4mph\n",
        weather_temp: 82.33,
        weather_condition: "Humid and Mostly Cloudy",
        weather_wind_mph: 7.4,
        weather_icon: "wi-night-alt-cloudy",
        weather_updated: "2022-08-18T12:00:22+00:00",
        quicktext:
          "Falcon 9 - Starlink-57 (4-23) - Sun Aug 28, 2022 01:52:00 UTC (L-9 days, 03:21:25) - https://rocketlaunch.live/launch/starlink-4-23 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-17T12:54:42+00:00",
      },
      {
        id: 38,
        cospar_id: "",
        sort_date: "1661776380",
        name: "Artemis 1 (EM-1)",
        provider: { id: 2, name: "NASA", slug: "nasa" },
        vehicle: { id: 15, name: "SLS", company_id: 2, slug: "sls" },
        pad: {
          id: 36,
          name: "LC-39B",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [
          {
            id: 35,
            name: "Artemis 1 (EM-1)",
            description:
              "On its maiden flight, the Space Launch System (SLS) will send an uncrewed Orion Multi-Purpose Crew Vehicle on a four to six-week mission to the Moon and back, including 6 days in a retrograde lunar orbit.",
          },
        ],
        mission_description:
          "On its maiden flight, the Space Launch System (SLS) will send an uncrewed Orion Multi-Purpose Crew Vehicle on a four to six-week mission to the Moon and back, including 6 days in a retrograde lunar orbit.",
        launch_description:
          "A NASA SLS rocket will launch the Artemis 1 (EM-1) mission on Monday, August 29, 2022 at 12:33 PM (UTC).",
        win_open: "2022-08-29T12:33Z",
        t0: null,
        win_close: "2022-08-29T14:33Z",
        est_date: { month: null, day: null, year: null, quarter: null },
        date_str: "Aug 29",
        tags: [
          { id: 48, text: "Lunar Orbit" },
          { id: 91, text: "Series: NASA Artemis" },
          { id: 23, text: "Test Flight" },
          { id: 21, text: "Uncrewed" },
          { id: 14, text: "Vehicle Debut" },
        ],
        slug: "em-1",
        weather_summary:
          "Humid and Partly Cloudy\nTemp: 77.67F\nWind: 4.92mph\n",
        weather_temp: 77.67,
        weather_condition: "Humid and Partly Cloudy",
        weather_wind_mph: 4.92,
        weather_icon: "wi-day-cloudy",
        weather_updated: "2022-08-18T12:00:23+00:00",
        quicktext:
          "SLS - Artemis 1 (EM-1) - Mon Aug 29, 2022 12:33:00 UTC (L-10 days, 14:02:25) - https://rocketlaunch.live/launch/em-1 for info/stream",
        media: [
          {
            id: 1079,
            media_url: "",
            youtube_vidid: "CMLD0Lp0JBg",
            featured: true,
            ldfeatured: true,
            approved: true,
          },
        ],
        result: -1,
        suborbital: false,
        modified: "2022-08-16T13:13:30+00:00",
      },
      {
        id: 2699,
        cospar_id: "",
        sort_date: "1661817596",
        name: "RS1 Flight 1",
        provider: { id: 142, name: "ABL Space", slug: "abl-space" },
        vehicle: { id: 121, name: "RS1", company_id: 142, slug: "rs1" },
        pad: {
          id: 126,
          name: "LP-3C",
          location: {
            id: 47,
            name: "Pacific Spaceport Complex - Alaska",
            state: "AK",
            statename: "Alaska",
            country: "United States",
            slug: "pacific-spaceport-co",
          },
        },
        missions: [{ id: 4199, name: "RS1 Flight 1", description: null }],
        mission_description: null,
        launch_description:
          "An ABL Space RS1 rocket will launch the RS1 Flight 1 mission. The launch date is currently targeted for August 29, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 8, day: 29, year: 2022, quarter: null },
        date_str: "Aug 29",
        tags: [
          { id: 23, text: "Test Flight" },
          { id: 14, text: "Vehicle Debut" },
        ],
        slug: "rs1-flight-1",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "RS1 - RS1 Flight 1 - Aug 29 (estimated) - https://rocketlaunch.live/launch/rs1-flight-1 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-12T02:27:10+00:00",
      },
      {
        id: 3187,
        cospar_id: "",
        sort_date: "1661990397",
        name: "Starlink (3-4)",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 1,
          name: "SLC-4E",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [{ id: 4912, name: "Starlink (3-4)", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Starlink (3-4) mission. The launch date is currently targeted for August, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 8, day: null, year: 2022, quarter: null },
        date_str: "Aug 2022",
        tags: [{ id: 92, text: "Series: SpaceX Starlink" }],
        slug: "starlink-3-4",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - Starlink (3-4) - Aug 2022 (estimated) - https://rocketlaunch.live/launch/starlink-3-4 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-12T02:18:15+00:00",
      },
      {
        id: 3190,
        cospar_id: "",
        sort_date: "1662508796",
        name: "Eutelsat Konnect VHTS",
        provider: { id: 4, name: "Arianespace", slug: "arianespace" },
        vehicle: { id: 2, name: "Ariane 5", company_id: 5, slug: "ariane-5" },
        pad: {
          id: 17,
          name: "ELA-3",
          location: {
            id: 70,
            name: "Guiana Space Centre",
            state: null,
            statename: null,
            country: "French Guiana",
            slug: "guiana-space-centre",
          },
        },
        missions: [
          { id: 4916, name: "Eutelsat Konnect VHTS", description: null },
        ],
        mission_description: null,
        launch_description:
          "An Arianespace Ariane 5 rocket will launch the Eutelsat Konnect VHTS mission. The launch date is currently targeted for September 06, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 6, year: 2022, quarter: null },
        date_str: "Sep 06",
        tags: [],
        slug: "eutelsat-konnect-vht",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Ariane 5 - Eutelsat Konnect VHTS - Sep 06 (estimated) - https://rocketlaunch.live/launch/eutelsat-konnect-vht for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-16T12:56:57+00:00",
      },
      {
        id: 2967,
        cospar_id: "",
        sort_date: "1662940796",
        name: '"To the Black"',
        provider: { id: 91, name: "Firefly", slug: "firefly" },
        vehicle: { id: 58, name: "Alpha", company_id: 91, slug: "alpha" },
        pad: {
          id: 38,
          name: "SLC-2W",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [{ id: 4606, name: "Alpha Flight 2", description: null }],
        mission_description: null,
        launch_description:
          'A Firefly Alpha rocket will launch the "To the Black" mission. The launch date is currently targeted for September 11, 2022 (UTC).',
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 11, year: 2022, quarter: null },
        date_str: "Sep 11",
        tags: [{ id: 23, text: "Test Flight" }],
        slug: "alpha-flight-2",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          'Alpha - "To the Black" - Sep 11 (estimated) - https://rocketlaunch.live/launch/alpha-flight-2 for info/stream',
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-09T15:40:16+00:00",
      },
      {
        id: 2969,
        cospar_id: "",
        sort_date: "1663286396",
        name: "SES-20 & SES-21",
        provider: {
          id: 3,
          name: "United Launch Alliance (ULA)",
          slug: "united-launch-alliance-ula",
        },
        vehicle: { id: 3, name: "Atlas V", company_id: 3, slug: "atlas-v" },
        pad: {
          id: 4,
          name: "SLC-41",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [{ id: 4608, name: "SES-20 & SES-21", description: null }],
        mission_description: null,
        launch_description:
          "A United Launch Alliance (ULA) Atlas V rocket will launch the SES-20 & SES-21 mission. The launch date is currently targeted for September 15, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 15, year: 2022, quarter: null },
        date_str: "Sep 15",
        tags: [],
        slug: "ses-20-ses-21",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Atlas V - SES-20 & SES-21 - Sep 15 (estimated) - https://rocketlaunch.live/launch/ses-20-ses-21 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-09T12:56:52+00:00",
      },
      {
        id: 2752,
        cospar_id: "",
        sort_date: "1663804796",
        name: "Soyuz MS-22",
        provider: { id: 13, name: "Roscosmos", slug: "roscosmos" },
        vehicle: { id: 20, name: "Soyuz-2", company_id: 13, slug: "soyuz-2" },
        pad: {
          id: 28,
          name: "LC-31/6",
          location: {
            id: 50,
            name: "Baikonur Cosmodrome",
            state: null,
            statename: null,
            country: "Kazakhstan",
            slug: "baikonur-cosmodrome",
          },
        },
        missions: [{ id: 4255, name: "Soyuz MS-22", description: null }],
        mission_description: null,
        launch_description:
          "A Roscosmos Soyuz-2 rocket will launch the Soyuz MS-22 mission. The launch date is currently targeted for September 21, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 21, year: 2022, quarter: null },
        date_str: "Sep 21",
        tags: [
          { id: 9, text: "Crewed" },
          { id: 17, text: "ISS Expedition" },
        ],
        slug: "soyuz-ms-22",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Soyuz-2 - Soyuz MS-22 - Sep 21 (estimated) - https://rocketlaunch.live/launch/soyuz-ms-22 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-01-06T03:49:03+00:00",
      },
      {
        id: 3108,
        cospar_id: "",
        sort_date: "1664495996",
        name: "Crew-5",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 2,
          name: "LC-39A",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [{ id: 4803, name: "Crew-5", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Crew-5 mission. The launch date is currently targeted for September 29, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: 29, year: 2022, quarter: null },
        date_str: "Sep 29",
        tags: [
          { id: 9, text: "Crewed" },
          { id: 22, text: "NASA Commercial Crew Program (CCP)" },
        ],
        slug: "crew-5",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - Crew-5 - Sep 29 (estimated) - https://rocketlaunch.live/launch/crew-5 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-07-21T20:58:51+00:00",
      },
      {
        id: 221,
        cospar_id: "",
        sort_date: "1664582397",
        name: "NROL-91",
        provider: {
          id: 3,
          name: "United Launch Alliance (ULA)",
          slug: "united-launch-alliance-ula",
        },
        vehicle: {
          id: 26,
          name: "Delta IV Heavy",
          company_id: 3,
          slug: "delta-iv-heavy",
        },
        pad: {
          id: 14,
          name: "SLC-6",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [{ id: 213, name: "NROL-91", description: null }],
        mission_description: null,
        launch_description:
          "A United Launch Alliance (ULA) Delta IV Heavy rocket will launch the NROL-91 mission. The launch date is currently targeted for September, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: null, year: 2022, quarter: null },
        date_str: "Sep 2022",
        tags: [{ id: 8, text: "Classified Payload" }],
        slug: "nrol-91",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Delta IV Heavy - NROL-91 - Sep 2022 (estimated) - https://rocketlaunch.live/launch/nrol-91 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-16T10:05:59+00:00",
      },
      {
        id: 228,
        cospar_id: "",
        sort_date: "1664582397",
        name: "Oceansat-3 (EOS-6)",
        provider: { id: 18, name: "ISRO", slug: "isro" },
        vehicle: { id: 21, name: "PSLV", company_id: 18, slug: "pslv" },
        pad: {
          id: 7,
          name: "FLP",
          location: {
            id: 67,
            name: "Satish Dhawan Space Centre",
            state: null,
            statename: null,
            country: "India",
            slug: "satish-dhawan-space-",
          },
        },
        missions: [{ id: 220, name: "Oceansat-3 (EOS-6)", description: null }],
        mission_description: null,
        launch_description:
          "An ISRO PSLV rocket will launch the Oceansat-3 (EOS-6) mission. The launch date is currently targeted for September, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: null, year: 2022, quarter: null },
        date_str: "Sep 2022",
        tags: [{ id: 25, text: "Earth Observation Satellite" }],
        slug: "oceansat-3",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "PSLV - Oceansat-3 (EOS-6) - Sep 2022 (estimated) - https://rocketlaunch.live/launch/oceansat-3 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T17:45:44+00:00",
      },
      {
        id: 3189,
        cospar_id: "",
        sort_date: "1664582397",
        name: "Starlink (4-20)",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 3,
          name: "SLC-40",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [
          { id: 4914, name: "Starlink (4-20)", description: null },
          { id: 4915, name: "Sherpa-LTC2", description: null },
        ],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Starlink (4-20) mission. The launch date is currently targeted for September, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: null, year: 2022, quarter: null },
        date_str: "Sep 2022",
        tags: [{ id: 92, text: "Series: SpaceX Starlink" }],
        slug: "starlink-4-20",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - Starlink (4-20) - Sep 2022 (estimated) - https://rocketlaunch.live/launch/starlink-4-20 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-16T12:56:18+00:00",
      },
      {
        id: 3191,
        cospar_id: "",
        sort_date: "1664582397",
        name: "Starlink (4-2)",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 2,
          name: "LC-39A",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [
          { id: 4917, name: "Starlink (4-2)", description: null },
          { id: 4918, name: "BlueWalker-3", description: null },
        ],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Starlink (4-2) mission. The launch date is currently targeted for September, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: null, year: 2022, quarter: null },
        date_str: "Sep 2022",
        tags: [{ id: 92, text: "Series: SpaceX Starlink" }],
        slug: "starlink-4-2",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - Starlink (4-2) - Sep 2022 (estimated) - https://rocketlaunch.live/launch/starlink-4-2 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-16T12:57:53+00:00",
      },
      {
        id: 3188,
        cospar_id: "",
        sort_date: "1664582397",
        name: '"The Owl Spreads Its Wings"',
        provider: { id: 26, name: "Rocket Lab", slug: "rocket-lab" },
        vehicle: {
          id: 18,
          name: "Electron",
          company_id: 26,
          slug: "electron",
        },
        pad: {
          id: 19,
          name: "LC-1A",
          location: {
            id: 20,
            name: "Rocket Lab Launch Complex, Mahia Peninsula",
            state: null,
            statename: null,
            country: "New Zealand",
            slug: "rocket-lab-launch-co",
          },
        },
        missions: [{ id: 4913, name: "StriX-1", description: null }],
        mission_description: null,
        launch_description:
          'A Rocket Lab Electron rocket will launch the "The Owl Spreads Its Wings" mission. The launch date is currently targeted for September, 2022 (UTC).',
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 9, day: null, year: 2022, quarter: null },
        date_str: "Sep 2022",
        tags: [],
        slug: "strix-1",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          'Electron - "The Owl Spreads Its Wings" - Sep 2022 (estimated) - https://rocketlaunch.live/launch/strix-1 for info/stream',
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-15T20:52:21+00:00",
      },
      {
        id: 1181,
        cospar_id: "",
        sort_date: "1664582398",
        name: '"Good Luck, Have Fun"',
        provider: {
          id: 127,
          name: "Relativity Space",
          slug: "relativity-space",
        },
        vehicle: {
          id: 92,
          name: "Terran 1",
          company_id: 127,
          slug: "terran-1",
        },
        pad: {
          id: 128,
          name: "SLC-16",
          location: {
            id: 62,
            name: "Cape Canaveral SFS",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-sfs",
          },
        },
        missions: [{ id: 1261, name: "Terran 1 Flight 1", description: null }],
        mission_description: null,
        launch_description:
          'A Relativity Space Terran 1 rocket will launch the "Good Luck, Have Fun" mission. The launch date is currently targeted for Q3 2022 (UTC).',
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: 2022, quarter: 3 },
        date_str: "Q3 2022",
        tags: [
          { id: 23, text: "Test Flight" },
          { id: 14, text: "Vehicle Debut" },
        ],
        slug: "terran-1-flight-1",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          'Terran 1 - "Good Luck, Have Fun" - Q3 2022 (estimated) - https://rocketlaunch.live/launch/terran-1-flight-1 for info/stream',
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T17:42:46+00:00",
      },
      {
        id: 2659,
        cospar_id: "",
        sort_date: "1664582398",
        name: "Full Stack Test Flight",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: {
          id: 119,
          name: "Super Heavy / Starship Prototype",
          company_id: 1,
          slug: "super-heavy-starship-prototype",
        },
        pad: {
          id: 114,
          name: "Launch Pad",
          location: {
            id: 89,
            name: "Boca Chica Launch Site",
            state: "TX",
            statename: "Texas",
            country: "United States",
            slug: "boca-chica-launch-si",
          },
        },
        missions: [
          {
            id: 4137,
            name: "Full Stack Test Flight",
            description:
              "As this is a test program, any dates and times are simply an estimate based on publicly known information.",
          },
        ],
        mission_description:
          "As this is a test program, any dates and times are simply an estimate based on publicly known information.",
        launch_description:
          "A SpaceX Super Heavy / Starship Prototype rocket will launch the Full Stack Test Flight mission. The launch date is currently targeted for Q3 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: null, day: null, year: 2022, quarter: 3 },
        date_str: "Q3 2022",
        tags: [{ id: 23, text: "Test Flight" }],
        slug: "full-stack-test-flig",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Super Heavy / Starship Prototype - Full Stack Test Flight - Q3 2022 (estimated) - https://rocketlaunch.live/launch/full-stack-test-flig for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-06-28T14:22:34+00:00",
      },
      {
        id: 2822,
        cospar_id: "",
        sort_date: "1665878396",
        name: "CRS2 NG-18 (Cygnus)",
        provider: {
          id: 88,
          name: "Northrop Grumman",
          slug: "northrop-grumman",
        },
        vehicle: { id: 5, name: "Antares", company_id: 88, slug: "antares" },
        pad: {
          id: 6,
          name: "Pad 0A",
          location: {
            id: 66,
            name: "Mid-Atlantic Regional Spaceport (Wallops Island)",
            state: "VA",
            statename: "Virginia",
            country: "United States",
            slug: "mid-atlantic-regiona",
          },
        },
        missions: [
          { id: 4385, name: "CRS2 NG-18 (Cygnus)", description: null },
        ],
        mission_description: null,
        launch_description:
          "A Northrop Grumman Antares rocket will launch the CRS2 NG-18 (Cygnus) mission. The launch date is currently targeted for October 15, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: 15, year: 2022, quarter: null },
        date_str: "Oct 15",
        tags: [{ id: 12, text: "ISS Cargo" }],
        slug: "crs2-ng-18",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Antares - CRS2 NG-18 (Cygnus) - Oct 15 (estimated) - https://rocketlaunch.live/launch/crs2-ng-18 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-07-30T12:00:52+00:00",
      },
      {
        id: 514,
        cospar_id: "",
        sort_date: "1667260797",
        name: "O3b mPower-1",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 56,
          name: "Pad TBD",
          location: {
            id: 52,
            name: "Cape Canaveral / KSC TBD",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-ksc-t",
          },
        },
        missions: [{ id: 512, name: "O3b mPower-1", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the O3b mPower-1 mission. The launch date is currently targeted for October, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: null, year: 2022, quarter: null },
        date_str: "Oct 2022",
        tags: [{ id: 24, text: "Communications Satellite" }],
        slug: "o3b-mpower-1",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - O3b mPower-1 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/o3b-mpower-1 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T17:44:00+00:00",
      },
      {
        id: 515,
        cospar_id: "",
        sort_date: "1667260797",
        name: "O3b mPower-2",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 56,
          name: "Pad TBD",
          location: {
            id: 52,
            name: "Cape Canaveral / KSC TBD",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-ksc-t",
          },
        },
        missions: [{ id: 513, name: "O3b mPower-2", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the O3b mPower-2 mission. The launch date is currently targeted for October, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: null, year: 2022, quarter: null },
        date_str: "Oct 2022",
        tags: [{ id: 24, text: "Communications Satellite" }],
        slug: "o3b-mpower-2",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - O3b mPower-2 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/o3b-mpower-2 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T17:44:17+00:00",
      },
      {
        id: 2970,
        cospar_id: "",
        sort_date: "1667260797",
        name: "SES-18 & SES-19",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 56,
          name: "Pad TBD",
          location: {
            id: 52,
            name: "Cape Canaveral / KSC TBD",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "cape-canaveral-ksc-t",
          },
        },
        missions: [{ id: 4609, name: "SES-18 & SES-19", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the SES-18 & SES-19 mission. The launch date is currently targeted for October, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 10, day: null, year: 2022, quarter: null },
        date_str: "Oct 2022",
        tags: [],
        slug: "ses-18-ses-19",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - SES-18 & SES-19 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/ses-18-ses-19 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-05-28T15:34:21+00:00",
      },
      {
        id: 323,
        cospar_id: "",
        sort_date: "1667347196",
        name: "JPSS-2",
        provider: {
          id: 3,
          name: "United Launch Alliance (ULA)",
          slug: "united-launch-alliance-ula",
        },
        vehicle: { id: 3, name: "Atlas V", company_id: 3, slug: "atlas-v" },
        pad: {
          id: 22,
          name: "SLC-3E",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [
          { id: 309, name: "JPSS-2", description: null },
          { id: 4188, name: "LOFTID", description: null },
        ],
        mission_description: null,
        launch_description:
          "A United Launch Alliance (ULA) Atlas V rocket will launch the JPSS-2 mission. The launch date is currently targeted for November 01, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 11, day: 1, year: 2022, quarter: null },
        date_str: "Nov 01",
        tags: [
          { id: 25, text: "Earth Observation Satellite" },
          { id: 29, text: "Polar Orbit" },
        ],
        slug: "jpss-2",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Atlas V - JPSS-2 - Nov 01 (estimated) - https://rocketlaunch.live/launch/jpss-2 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T20:14:20+00:00",
      },
      {
        id: 404,
        cospar_id: "",
        sort_date: "1668556796",
        name: "SWOT",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 1,
          name: "SLC-4E",
          location: {
            id: 60,
            name: "Vandenberg SFB",
            state: "CA",
            statename: "California",
            country: "United States",
            slug: "vandenberg-sfb",
          },
        },
        missions: [{ id: 392, name: "SWOT", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the SWOT mission. The launch date is currently targeted for November 15, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 11, day: 15, year: 2022, quarter: null },
        date_str: "Nov 15",
        tags: [{ id: 25, text: "Earth Observation Satellite" }],
        slug: "swot",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - SWOT - Nov 15 (estimated) - https://rocketlaunch.live/launch/swot for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-03-25T22:51:49+00:00",
      },
      {
        id: 1208,
        cospar_id: "",
        sort_date: "1669852797",
        name: "USSF-67",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: {
          id: 7,
          name: "Falcon Heavy",
          company_id: 1,
          slug: "falcon-heavy",
        },
        pad: {
          id: 2,
          name: "LC-39A",
          location: {
            id: 61,
            name: "Kennedy Space Center",
            state: "FL",
            statename: "Florida",
            country: "United States",
            slug: "kennedy-space-center",
          },
        },
        missions: [{ id: 1288, name: "USSF-67", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon Heavy rocket will launch the USSF-67 mission. The launch date is currently targeted for November, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 11, day: null, year: 2022, quarter: null },
        date_str: "Nov 2022",
        tags: [],
        slug: "ussf-67",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon Heavy - USSF-67 - Nov 2022 (estimated) - https://rocketlaunch.live/launch/ussf-67 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T20:16:57+00:00",
      },
      {
        id: 3172,
        cospar_id: "",
        sort_date: "1669852797",
        name: "Transporter-6",
        provider: { id: 1, name: "SpaceX", slug: "spacex" },
        vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
        pad: {
          id: 55,
          name: "Pad TBD",
          location: {
            id: 68,
            name: "United States TBD",
            state: null,
            statename: null,
            country: "United States",
            slug: "united-states-tbd",
          },
        },
        missions: [{ id: 4898, name: "Transporter-6", description: null }],
        mission_description: null,
        launch_description:
          "A SpaceX Falcon 9 rocket will launch the Transporter-6 mission. The launch date is currently targeted for November, 2022 (UTC).",
        win_open: null,
        t0: null,
        win_close: null,
        est_date: { month: 11, day: null, year: 2022, quarter: null },
        date_str: "Nov 2022",
        tags: [],
        slug: "transporter-6",
        weather_summary: null,
        weather_temp: null,
        weather_condition: null,
        weather_wind_mph: null,
        weather_icon: null,
        weather_updated: null,
        quicktext:
          "Falcon 9 - Transporter-6 - Nov 2022 (estimated) - https://rocketlaunch.live/launch/transporter-6 for info/stream",
        media: [],
        result: -1,
        suborbital: false,
        modified: "2022-08-05T19:59:52+00:00",
      },
    ],
  };

  return (
    <>
      <div id="home_title_container">
        <img id="home_title" src={title} alt="flight_horizons" />
      </div>
      <UpcomingLaunches />
      <div id="horizon_container">
        <img id="horizon_image" src={horizon} alt="image_of_horizon" />
      </div>
    </>
  );
}

export default Home;
