import { useEffect, useState } from "react";
import Entry from "./Components/Entry";
import Home from "./Components/Home";

function App() {
  const [upcomingLaunches, setUpcomingLaunches] = useState([]);
  const [animate, setAnimate] = useState(true);
  const [entry, setEntry] = useState(true);

  // what part of this codebase would be really bad if it broke?
  // - it would be bad if we didnt see an animation on first load
  // - '' '' '' '' '' '' animation plays on every reload
  // - '' '' '' '' '' '' we didn't transition to the home screen after initial animation

  const fetchData = async () => {
    console.log('in fetchData')
    const response = await fetch("https://fdo.rocketlaunch.live/json/launches?key=8d15b6e5-4f07-4c6b-b60a-b37c26603bed")
    if (!response.ok) {
      throw new Error("Network response was not OK")
      }
    return response.json()
    }

    const hardcodeLaunches = {
      valid_auth: true,
      count: 25,
      limit: 25,
      total: 120,
      last_page: 5,
      result: [
        {
          id: 3190,
          cospar_id: "",
          sort_date: "1662587100",
          name: "Eutelsat Konnect VHTS",
          provider: { id: 4, name: "Arianespace", slug: "arianespace" },
          vehicle: { id: 2, name: "Ariane 5", company_id: 5, slug: "ariane-5" },
          pad: {
            id: 17,
            name: "ELA-3",
            location: {
              id: 70,
              name: "Guiana Space Centre",
              state: null,
              statename: null,
              country: "French Guiana",
              slug: "guiana-space-centre",
            },
          },
          missions: [
            { id: 4916, name: "Eutelsat Konnect VHTS", description: null },
          ],
          mission_description: null,
          launch_description:
            "An Arianespace Ariane 5 rocket will launch the Eutelsat Konnect VHTS mission on Wednesday, September 7, 2022 at 9:45 PM (UTC).",
          win_open: "2022-09-07T21:45Z",
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: null, quarter: null },
          date_str: "Sep 07",
          tags: [],
          slug: "eutelsat-konnect-vht",
          weather_summary:
            "Humid and Partly Cloudy\nTemp: 82.72F\nWind: 8.71mph\n",
          weather_temp: 82.72,
          weather_condition: "Humid and Partly Cloudy",
          weather_wind_mph: 8.71,
          weather_icon: "wi-day-cloudy",
          weather_updated: "2022-09-07T00:00:23+00:00",
          quicktext:
            "Ariane 5 - Eutelsat Konnect VHTS - Wed Sep 07, 2022 21:45:00 UTC (L-18:10:22) - https://rocketlaunch.live/launch/eutelsat-konnect-vht for info/stream",
          media: [
            {
              id: 1089,
              media_url: "",
              youtube_vidid: "FhHUbSuZN_8",
              featured: true,
              ldfeatured: true,
              approved: true,
            },
          ],
          result: -1,
          suborbital: false,
          modified: "2022-09-06T16:01:12+00:00",
        },
        {
          id: 2699,
          cospar_id: "",
          sort_date: "1662847200",
          name: "RS1 Flight 1",
          provider: { id: 142, name: "ABL Space", slug: "abl-space" },
          vehicle: { id: 121, name: "RS1", company_id: 142, slug: "rs1" },
          pad: {
            id: 126,
            name: "LP-3C",
            location: {
              id: 47,
              name: "Pacific Spaceport Complex - Alaska",
              state: "AK",
              statename: "Alaska",
              country: "United States",
              slug: "pacific-spaceport-co",
            },
          },
          missions: [{ id: 4199, name: "RS1 Flight 1", description: null }],
          mission_description: null,
          launch_description:
            "An ABL Space RS1 rocket will launch the RS1 Flight 1 mission on Saturday, September 10, 2022 at 10:00 PM (UTC).",
          win_open: "2022-09-10T22:00Z",
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: null, quarter: null },
          date_str: "Sep 10",
          tags: [
            { id: 23, text: "Test Flight" },
            { id: 14, text: "Vehicle Debut" },
          ],
          slug: "rs1-flight-1",
          weather_summary: "Possible Drizzle\nTemp: 53.39F\nWind: 15.81mph\n",
          weather_temp: 53.39,
          weather_condition: "Possible Drizzle",
          weather_wind_mph: 15.81,
          weather_icon: "wi-rain",
          weather_updated: "2022-09-07T00:00:23+00:00",
          quicktext:
            "RS1 - RS1 Flight 1 - Sat Sep 10, 2022 22:00:00 UTC (L-3 days, 18:25:22) - https://rocketlaunch.live/launch/rs1-flight-1 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-09-04T11:21:57+00:00",
        },
        {
          id: 3191,
          cospar_id: "",
          sort_date: "1662853860",
          name: "Starlink (4-2)",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 2,
            name: "LC-39A",
            location: {
              id: 61,
              name: "Kennedy Space Center",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "kennedy-space-center",
            },
          },
          missions: [
            { id: 4917, name: "Starlink (4-2)", description: null },
            { id: 4918, name: "BlueWalker-3", description: null },
          ],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the Starlink (4-2) mission on Saturday, September 10, 2022 at 11:51 PM (UTC).",
          win_open: "2022-09-10T23:51Z",
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: null, quarter: null },
          date_str: "Sep 10",
          tags: [{ id: 92, text: "Series: SpaceX Starlink" }],
          slug: "starlink-4-2",
          weather_summary:
            "Humid and Mostly Cloudy\nTemp: 90.55F\nWind: 9.78mph\n",
          weather_temp: 90.55,
          weather_condition: "Humid and Mostly Cloudy",
          weather_wind_mph: 9.78,
          weather_icon: "wi-day-cloudy",
          weather_updated: "2022-09-07T00:00:24+00:00",
          quicktext:
            "Falcon 9 - Starlink (4-2) - Sat Sep 10, 2022 23:51:00 UTC (L-3 days, 20:16:22) - https://rocketlaunch.live/launch/starlink-4-2 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-09-03T22:13:34+00:00",
        },
        {
          id: 2967,
          cospar_id: "",
          sort_date: "1662933600",
          name: '"To the Black"',
          provider: { id: 91, name: "Firefly", slug: "firefly" },
          vehicle: { id: 58, name: "Alpha", company_id: 91, slug: "alpha" },
          pad: {
            id: 38,
            name: "SLC-2W",
            location: {
              id: 60,
              name: "Vandenberg SFB",
              state: "CA",
              statename: "California",
              country: "United States",
              slug: "vandenberg-sfb",
            },
          },
          missions: [{ id: 4606, name: "Alpha Flight 2", description: null }],
          mission_description: null,
          launch_description:
            'A Firefly Alpha rocket will launch the "To the Black" mission on Sunday, September 11, 2022 at 10:00 PM (UTC).',
          win_open: "2022-09-11T22:00Z",
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: null, quarter: null },
          date_str: "Sep 11",
          tags: [{ id: 23, text: "Test Flight" }],
          slug: "alpha-flight-2",
          weather_summary: "Mostly Cloudy\nTemp: 72.63F\nWind: 8.78mph\n",
          weather_temp: 72.63,
          weather_condition: "Mostly Cloudy",
          weather_wind_mph: 8.78,
          weather_icon: "wi-day-cloudy",
          weather_updated: "2022-09-07T00:00:24+00:00",
          quicktext:
            'Alpha - "To the Black" - Sun Sep 11, 2022 22:00:00 UTC (L-4 days, 18:25:22) - https://rocketlaunch.live/launch/alpha-flight-2 for info/stream',
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-22T15:12:58+00:00",
        },
        {
          id: 3188,
          cospar_id: "",
          sort_date: "1663187400",
          name: '"The Owl Spreads Its Wings"',
          provider: { id: 26, name: "Rocket Lab", slug: "rocket-lab" },
          vehicle: {
            id: 18,
            name: "Electron",
            company_id: 26,
            slug: "electron",
          },
          pad: {
            id: 19,
            name: "LC-1A",
            location: {
              id: 20,
              name: "Rocket Lab Launch Complex, Mahia Peninsula",
              state: null,
              statename: null,
              country: "New Zealand",
              slug: "rocket-lab-launch-co",
            },
          },
          missions: [{ id: 4913, name: "StriX-1", description: null }],
          mission_description: null,
          launch_description:
            'A Rocket Lab Electron rocket will launch the "The Owl Spreads Its Wings" mission on Wednesday, September 14, 2022 at 8:30 PM (UTC).',
          win_open: "2022-09-14T20:30Z",
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: null, quarter: null },
          date_str: "Sep 14",
          tags: [],
          slug: "strix-1",
          weather_summary: "Overcast\nTemp: 50F\nWind: 18.73mph\n",
          weather_temp: 50,
          weather_condition: "Overcast",
          weather_wind_mph: 18.73,
          weather_icon: "wi-cloudy",
          weather_updated: "2022-09-07T00:00:24+00:00",
          quicktext:
            'Electron - "The Owl Spreads Its Wings" - Wed Sep 14, 2022 20:30:00 UTC (L-7 days, 16:55:22) - https://rocketlaunch.live/launch/strix-1 for info/stream',
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-31T20:38:22+00:00",
        },
        {
          id: 2752,
          cospar_id: "",
          sort_date: "1663768440",
          name: "Soyuz MS-22",
          provider: { id: 13, name: "Roscosmos", slug: "roscosmos" },
          vehicle: { id: 20, name: "Soyuz-2", company_id: 13, slug: "soyuz-2" },
          pad: {
            id: 28,
            name: "LC-31/6",
            location: {
              id: 50,
              name: "Baikonur Cosmodrome",
              state: null,
              statename: null,
              country: "Kazakhstan",
              slug: "baikonur-cosmodrome",
            },
          },
          missions: [{ id: 4255, name: "Soyuz MS-22", description: null }],
          mission_description: null,
          launch_description:
            "A Roscosmos Soyuz-2 rocket will launch the Soyuz MS-22 mission on Wednesday, September 21, 2022 at 1:54 PM (UTC).",
          win_open: "2022-09-21T13:54Z",
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: null, quarter: null },
          date_str: "Sep 21",
          tags: [
            { id: 9, text: "Crewed" },
            { id: 17, text: "ISS Expedition" },
          ],
          slug: "soyuz-ms-22",
          weather_summary: "\nTemp: 68.51F\nWind: 7.78mph\n",
          weather_temp: 68.51,
          weather_condition: null,
          weather_wind_mph: 7.78,
          weather_icon: "",
          weather_updated: "2022-09-07T00:00:25+00:00",
          quicktext:
            "Soyuz-2 - Soyuz MS-22 - Wed Sep 21, 2022 13:54:00 UTC (L-14 days, 10:19:22) - https://rocketlaunch.live/launch/soyuz-ms-22 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-09-04T01:32:26+00:00",
        },
        {
          id: 221,
          cospar_id: "",
          sort_date: "1664063996",
          name: "NROL-91",
          provider: {
            id: 3,
            name: "United Launch Alliance (ULA)",
            slug: "united-launch-alliance-ula",
          },
          vehicle: {
            id: 26,
            name: "Delta IV Heavy",
            company_id: 3,
            slug: "delta-iv-heavy",
          },
          pad: {
            id: 14,
            name: "SLC-6",
            location: {
              id: 60,
              name: "Vandenberg SFB",
              state: "CA",
              statename: "California",
              country: "United States",
              slug: "vandenberg-sfb",
            },
          },
          missions: [{ id: 213, name: "NROL-91", description: null }],
          mission_description: null,
          launch_description:
            "A United Launch Alliance (ULA) Delta IV Heavy rocket will launch the NROL-91 mission. The launch date is currently targeted for September 24, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 9, day: 24, year: 2022, quarter: null },
          date_str: "Sep 24",
          tags: [{ id: 8, text: "Classified Payload" }],
          slug: "nrol-91",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Delta IV Heavy - NROL-91 - Sep 24 (estimated) - https://rocketlaunch.live/launch/nrol-91 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-24T20:56:24+00:00",
        },
        {
          id: 38,
          cospar_id: "",
          sort_date: "1664582397",
          name: "Artemis I (EM-1)",
          provider: { id: 2, name: "NASA", slug: "nasa" },
          vehicle: { id: 15, name: "SLS", company_id: 2, slug: "sls" },
          pad: {
            id: 36,
            name: "LC-39B",
            location: {
              id: 61,
              name: "Kennedy Space Center",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "kennedy-space-center",
            },
          },
          missions: [
            {
              id: 35,
              name: "Artemis I (EM-1)",
              description:
                "On its debut flight, the Space Launch System (SLS) will send an uncrewed Orion Multi-Purpose Crew Vehicle on a four to six-week mission to the Moon and back, including 6 days in a retrograde lunar orbit.",
            },
          ],
          mission_description:
            "On its debut flight, the Space Launch System (SLS) will send an uncrewed Orion Multi-Purpose Crew Vehicle on a four to six-week mission to the Moon and back, including 6 days in a retrograde lunar orbit.",
          launch_description:
            "A NASA SLS rocket will launch the Artemis I (EM-1) mission. The launch date is currently targeted for September, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 9, day: null, year: 2022, quarter: null },
          date_str: "Sep 2022",
          tags: [
            { id: 48, text: "Lunar Orbit" },
            { id: 91, text: "Series: NASA Artemis" },
            { id: 23, text: "Test Flight" },
            { id: 21, text: "Uncrewed" },
            { id: 14, text: "Vehicle Debut" },
          ],
          slug: "em-1",
          weather_summary:
            "Humid and Mostly Cloudy\nTemp: 89.38F\nWind: 8.08mph\n",
          weather_temp: 89.38,
          weather_condition: "Humid and Mostly Cloudy",
          weather_wind_mph: 8.08,
          weather_icon: "wi-day-cloudy",
          weather_updated: "2022-09-03T12:00:22+00:00",
          quicktext:
            "SLS - Artemis I (EM-1) - Sep 2022 (estimated) - https://rocketlaunch.live/launch/em-1 for info/stream",
          media: [
            {
              id: 1079,
              media_url: "",
              youtube_vidid: "CMLD0Lp0JBg",
              featured: true,
              ldfeatured: true,
              approved: true,
            },
          ],
          result: -1,
          suborbital: false,
          modified: "2022-09-03T21:38:04+00:00",
        },
        {
          id: 228,
          cospar_id: "",
          sort_date: "1664582397",
          name: "Oceansat-3 (EOS-6)",
          provider: { id: 18, name: "ISRO", slug: "isro" },
          vehicle: { id: 21, name: "PSLV", company_id: 18, slug: "pslv" },
          pad: {
            id: 7,
            name: "FLP",
            location: {
              id: 67,
              name: "Satish Dhawan Space Centre",
              state: null,
              statename: null,
              country: "India",
              slug: "satish-dhawan-space-",
            },
          },
          missions: [
            { id: 220, name: "Oceansat-3 (EOS-6)", description: null },
          ],
          mission_description: null,
          launch_description:
            "An ISRO PSLV rocket will launch the Oceansat-3 (EOS-6) mission. The launch date is currently targeted for September, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 9, day: null, year: 2022, quarter: null },
          date_str: "Sep 2022",
          tags: [{ id: 25, text: "Earth Observation Satellite" }],
          slug: "oceansat-3",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "PSLV - Oceansat-3 (EOS-6) - Sep 2022 (estimated) - https://rocketlaunch.live/launch/oceansat-3 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-05T17:45:44+00:00",
        },
        {
          id: 2969,
          cospar_id: "",
          sort_date: "1664582397",
          name: "SES-20 & SES-21",
          provider: {
            id: 3,
            name: "United Launch Alliance (ULA)",
            slug: "united-launch-alliance-ula",
          },
          vehicle: { id: 3, name: "Atlas V", company_id: 3, slug: "atlas-v" },
          pad: {
            id: 4,
            name: "SLC-41",
            location: {
              id: 62,
              name: "Cape Canaveral SFS",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "cape-canaveral-sfs",
            },
          },
          missions: [{ id: 4608, name: "SES-20 & SES-21", description: null }],
          mission_description: null,
          launch_description:
            "A United Launch Alliance (ULA) Atlas V rocket will launch the SES-20 & SES-21 mission. The launch date is currently targeted for September, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 9, day: null, year: 2022, quarter: null },
          date_str: "Sep 2022",
          tags: [],
          slug: "ses-20-ses-21",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Atlas V - SES-20 & SES-21 - Sep 2022 (estimated) - https://rocketlaunch.live/launch/ses-20-ses-21 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-22T12:23:25+00:00",
        },
        {
          id: 1181,
          cospar_id: "",
          sort_date: "1664582398",
          name: '"Good Luck, Have Fun"',
          provider: {
            id: 127,
            name: "Relativity Space",
            slug: "relativity-space",
          },
          vehicle: {
            id: 92,
            name: "Terran 1",
            company_id: 127,
            slug: "terran-1",
          },
          pad: {
            id: 128,
            name: "SLC-16",
            location: {
              id: 62,
              name: "Cape Canaveral SFS",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "cape-canaveral-sfs",
            },
          },
          missions: [
            { id: 1261, name: "Terran 1 Flight 1", description: null },
          ],
          mission_description: null,
          launch_description:
            'A Relativity Space Terran 1 rocket will launch the "Good Luck, Have Fun" mission. The launch date is currently targeted for Q3 2022 (UTC).',
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: 2022, quarter: 3 },
          date_str: "Q3 2022",
          tags: [
            { id: 23, text: "Test Flight" },
            { id: 14, text: "Vehicle Debut" },
          ],
          slug: "terran-1-flight-1",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            'Terran 1 - "Good Luck, Have Fun" - Q3 2022 (estimated) - https://rocketlaunch.live/launch/terran-1-flight-1 for info/stream',
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-05T17:42:46+00:00",
        },
        {
          id: 3108,
          cospar_id: "",
          sort_date: "1664815500",
          name: "Crew-5",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 2,
            name: "LC-39A",
            location: {
              id: 61,
              name: "Kennedy Space Center",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "kennedy-space-center",
            },
          },
          missions: [{ id: 4803, name: "Crew-5", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the Crew-5 mission on Monday, October 3, 2022 at 4:45 PM (UTC).",
          win_open: "2022-10-03T16:45Z",
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: null, quarter: null },
          date_str: "Oct 03",
          tags: [
            { id: 9, text: "Crewed" },
            { id: 22, text: "NASA Commercial Crew Program (CCP)" },
          ],
          slug: "crew-5",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon 9 - Crew-5 - Mon Oct 03, 2022 16:45:00 UTC (L-26 days, 13:10:22) - https://rocketlaunch.live/launch/crew-5 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-09-04T01:29:22+00:00",
        },
        {
          id: 2822,
          cospar_id: "",
          sort_date: "1665878396",
          name: "CRS2 NG-18 (Cygnus)",
          provider: {
            id: 88,
            name: "Northrop Grumman",
            slug: "northrop-grumman",
          },
          vehicle: { id: 5, name: "Antares", company_id: 88, slug: "antares" },
          pad: {
            id: 6,
            name: "Pad 0A",
            location: {
              id: 66,
              name: "Mid-Atlantic Regional Spaceport (Wallops Island)",
              state: "VA",
              statename: "Virginia",
              country: "United States",
              slug: "mid-atlantic-regiona",
            },
          },
          missions: [
            { id: 4385, name: "CRS2 NG-18 (Cygnus)", description: null },
          ],
          mission_description: null,
          launch_description:
            "A Northrop Grumman Antares rocket will launch the CRS2 NG-18 (Cygnus) mission. The launch date is currently targeted for October 15, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 10, day: 15, year: 2022, quarter: null },
          date_str: "Oct 15",
          tags: [{ id: 12, text: "ISS Cargo" }],
          slug: "crs2-ng-18",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Antares - CRS2 NG-18 (Cygnus) - Oct 15 (estimated) - https://rocketlaunch.live/launch/crs2-ng-18 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-07-30T12:00:52+00:00",
        },
        {
          id: 3202,
          cospar_id: "",
          sort_date: "1666736340",
          name: "Progress MS-21",
          provider: { id: 13, name: "Roscosmos", slug: "roscosmos" },
          vehicle: { id: 20, name: "Soyuz-2", company_id: 13, slug: "soyuz-2" },
          pad: {
            id: 28,
            name: "LC-31/6",
            location: {
              id: 50,
              name: "Baikonur Cosmodrome",
              state: null,
              statename: null,
              country: "Kazakhstan",
              slug: "baikonur-cosmodrome",
            },
          },
          missions: [{ id: 4929, name: "Progress MS-21", description: null }],
          mission_description: null,
          launch_description:
            "A Roscosmos Soyuz-2 rocket will launch the Progress MS-21 mission on Tuesday, October 25, 2022 at 10:19 PM (UTC).",
          win_open: "2022-10-25T22:19Z",
          t0: null,
          win_close: null,
          est_date: { month: null, day: null, year: null, quarter: null },
          date_str: "Oct 25",
          tags: [{ id: 12, text: "ISS Cargo" }],
          slug: "progress-ms-21",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Soyuz-2 - Progress MS-21 - Tue Oct 25, 2022 22:19:00 UTC (L-18 days, 18:44:22) - https://rocketlaunch.live/launch/progress-ms-21 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-09-04T01:33:19+00:00",
        },
        {
          id: 514,
          cospar_id: "",
          sort_date: "1667260797",
          name: "O3b mPower-1",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 56,
            name: "Pad TBD",
            location: {
              id: 52,
              name: "Cape Canaveral / KSC TBD",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "cape-canaveral-ksc-t",
            },
          },
          missions: [{ id: 512, name: "O3b mPower-1", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the O3b mPower-1 mission. The launch date is currently targeted for October, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 10, day: null, year: 2022, quarter: null },
          date_str: "Oct 2022",
          tags: [{ id: 24, text: "Communications Satellite" }],
          slug: "o3b-mpower-1",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon 9 - O3b mPower-1 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/o3b-mpower-1 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-05T17:44:00+00:00",
        },
        {
          id: 515,
          cospar_id: "",
          sort_date: "1667260797",
          name: "O3b mPower-2",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 56,
            name: "Pad TBD",
            location: {
              id: 52,
              name: "Cape Canaveral / KSC TBD",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "cape-canaveral-ksc-t",
            },
          },
          missions: [{ id: 513, name: "O3b mPower-2", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the O3b mPower-2 mission. The launch date is currently targeted for October, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 10, day: null, year: 2022, quarter: null },
          date_str: "Oct 2022",
          tags: [{ id: 24, text: "Communications Satellite" }],
          slug: "o3b-mpower-2",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon 9 - O3b mPower-2 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/o3b-mpower-2 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-05T17:44:17+00:00",
        },
        {
          id: 2970,
          cospar_id: "",
          sort_date: "1667260797",
          name: "SES-18 & SES-19",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 56,
            name: "Pad TBD",
            location: {
              id: 52,
              name: "Cape Canaveral / KSC TBD",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "cape-canaveral-ksc-t",
            },
          },
          missions: [{ id: 4609, name: "SES-18 & SES-19", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the SES-18 & SES-19 mission. The launch date is currently targeted for October, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 10, day: null, year: 2022, quarter: null },
          date_str: "Oct 2022",
          tags: [],
          slug: "ses-18-ses-19",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon 9 - SES-18 & SES-19 - Oct 2022 (estimated) - https://rocketlaunch.live/launch/ses-18-ses-19 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-05-28T15:34:21+00:00",
        },
        {
          id: 323,
          cospar_id: "",
          sort_date: "1667347196",
          name: "JPSS-2",
          provider: {
            id: 3,
            name: "United Launch Alliance (ULA)",
            slug: "united-launch-alliance-ula",
          },
          vehicle: { id: 3, name: "Atlas V", company_id: 3, slug: "atlas-v" },
          pad: {
            id: 22,
            name: "SLC-3E",
            location: {
              id: 60,
              name: "Vandenberg SFB",
              state: "CA",
              statename: "California",
              country: "United States",
              slug: "vandenberg-sfb",
            },
          },
          missions: [
            { id: 309, name: "JPSS-2", description: null },
            { id: 4188, name: "LOFTID", description: null },
          ],
          mission_description: null,
          launch_description:
            "A United Launch Alliance (ULA) Atlas V rocket will launch the JPSS-2 mission. The launch date is currently targeted for November 01, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 11, day: 1, year: 2022, quarter: null },
          date_str: "Nov 01",
          tags: [
            { id: 25, text: "Earth Observation Satellite" },
            { id: 29, text: "Polar Orbit" },
          ],
          slug: "jpss-2",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Atlas V - JPSS-2 - Nov 01 (estimated) - https://rocketlaunch.live/launch/jpss-2 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-05T20:14:20+00:00",
        },
        {
          id: 3172,
          cospar_id: "",
          sort_date: "1667865596",
          name: "Transporter-6",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 3,
            name: "SLC-40",
            location: {
              id: 62,
              name: "Cape Canaveral SFS",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "cape-canaveral-sfs",
            },
          },
          missions: [{ id: 4898, name: "Transporter-6", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the Transporter-6 mission. The launch date is currently targeted for November 07, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 11, day: 7, year: 2022, quarter: null },
          date_str: "Nov 07",
          tags: [],
          slug: "transporter-6",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon 9 - Transporter-6 - Nov 07 (estimated) - https://rocketlaunch.live/launch/transporter-6 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-19T17:33:55+00:00",
        },
        {
          id: 1208,
          cospar_id: "",
          sort_date: "1669852797",
          name: "USSF-67",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: {
            id: 7,
            name: "Falcon Heavy",
            company_id: 1,
            slug: "falcon-heavy",
          },
          pad: {
            id: 2,
            name: "LC-39A",
            location: {
              id: 61,
              name: "Kennedy Space Center",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "kennedy-space-center",
            },
          },
          missions: [{ id: 1288, name: "USSF-67", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon Heavy rocket will launch the USSF-67 mission. The launch date is currently targeted for November, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 11, day: null, year: 2022, quarter: null },
          date_str: "Nov 2022",
          tags: [],
          slug: "ussf-67",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon Heavy - USSF-67 - Nov 2022 (estimated) - https://rocketlaunch.live/launch/ussf-67 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-05T20:16:57+00:00",
        },
        {
          id: 404,
          cospar_id: "",
          sort_date: "1670284796",
          name: "SWOT",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 1,
            name: "SLC-4E",
            location: {
              id: 60,
              name: "Vandenberg SFB",
              state: "CA",
              statename: "California",
              country: "United States",
              slug: "vandenberg-sfb",
            },
          },
          missions: [{ id: 392, name: "SWOT", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the SWOT mission. The launch date is currently targeted for December 05, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 12, day: 5, year: 2022, quarter: null },
          date_str: "Dec 05",
          tags: [{ id: 25, text: "Earth Observation Satellite" }],
          slug: "swot",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon 9 - SWOT - Dec 05 (estimated) - https://rocketlaunch.live/launch/swot for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-26T16:41:41+00:00",
        },
        {
          id: 465,
          cospar_id: "",
          sort_date: "1672531197",
          name: "USSF-44",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: {
            id: 7,
            name: "Falcon Heavy",
            company_id: 1,
            slug: "falcon-heavy",
          },
          pad: {
            id: 2,
            name: "LC-39A",
            location: {
              id: 61,
              name: "Kennedy Space Center",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "kennedy-space-center",
            },
          },
          missions: [{ id: 448, name: "USSF-44", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon Heavy rocket will launch the USSF-44 mission. The launch date is currently targeted for December, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 12, day: null, year: 2022, quarter: null },
          date_str: "Dec 2022",
          tags: [],
          slug: "afspc-44",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon Heavy - USSF-44 - Dec 2022 (estimated) - https://rocketlaunch.live/launch/afspc-44 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-06-28T14:21:13+00:00",
        },
        {
          id: 600,
          cospar_id: null,
          sort_date: "1672531197",
          name: "PACE",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 3,
            name: "SLC-40",
            location: {
              id: 62,
              name: "Cape Canaveral SFS",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "cape-canaveral-sfs",
            },
          },
          missions: [{ id: 626, name: "PACE", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the PACE mission. The launch date is currently targeted for December, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 12, day: null, year: 2022, quarter: null },
          date_str: "Dec 2022",
          tags: [],
          slug: "pace",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon 9 - PACE - Dec 2022 (estimated) - https://rocketlaunch.live/launch/pace for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2020-02-04T22:48:59+00:00",
        },
        {
          id: 2820,
          cospar_id: "",
          sort_date: "1672531197",
          name: "Polaris Dawn",
          provider: { id: 1, name: "SpaceX", slug: "spacex" },
          vehicle: { id: 1, name: "Falcon 9", company_id: 1, slug: "falcon-9" },
          pad: {
            id: 2,
            name: "LC-39A",
            location: {
              id: 61,
              name: "Kennedy Space Center",
              state: "FL",
              statename: "Florida",
              country: "United States",
              slug: "kennedy-space-center",
            },
          },
          missions: [{ id: 4383, name: "Polaris Dawn", description: null }],
          mission_description: null,
          launch_description:
            "A SpaceX Falcon 9 rocket will launch the Polaris Dawn mission. The launch date is currently targeted for December, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 12, day: null, year: 2022, quarter: null },
          date_str: "Dec 2022",
          tags: [{ id: 9, text: "Crewed" }],
          slug: "polaris-dawn",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Falcon 9 - Polaris Dawn - Dec 2022 (estimated) - https://rocketlaunch.live/launch/polaris-dawn for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-08-02T20:44:35+00:00",
        },
        {
          id: 2855,
          cospar_id: "",
          sort_date: "1672531197",
          name: "HawkEye 360 Flight 1/3",
          provider: { id: 26, name: "Rocket Lab", slug: "rocket-lab" },
          vehicle: {
            id: 18,
            name: "Electron",
            company_id: 26,
            slug: "electron",
          },
          pad: {
            id: 12,
            name: "Rocket Lab LC-2",
            location: {
              id: 66,
              name: "Mid-Atlantic Regional Spaceport (Wallops Island)",
              state: "VA",
              statename: "Virginia",
              country: "United States",
              slug: "mid-atlantic-regiona",
            },
          },
          missions: [
            { id: 4419, name: "HawkEye 360 Flight 1/3", description: null },
          ],
          mission_description: null,
          launch_description:
            "A Rocket Lab Electron rocket will launch the HawkEye 360 Flight 1/3 mission. The launch date is currently targeted for December, 2022 (UTC).",
          win_open: null,
          t0: null,
          win_close: null,
          est_date: { month: 12, day: null, year: 2022, quarter: null },
          date_str: "Dec 2022",
          tags: [],
          slug: "hawkeye-360",
          weather_summary: null,
          weather_temp: null,
          weather_condition: null,
          weather_wind_mph: null,
          weather_icon: null,
          weather_updated: null,
          quicktext:
            "Electron - HawkEye 360 Flight 1/3 - Dec 2022 (estimated) - https://rocketlaunch.live/launch/hawkeye-360 for info/stream",
          media: [],
          result: -1,
          suborbital: false,
          modified: "2022-04-20T17:07:26+00:00",
        },
      ],
    };


  // useEffect(() => {
  //   console.log('in use effect')
  //   fetchData()
  //   .then((data) => {
  //     console.log("data:", data)
  //     setUpcomingLaunches(data)
  //   })
  //   .catch((error) => {
  //     console.error("Error:", error)
  //   })
  // }, [])

  useEffect(() => {
    if (window.sessionStorage.getItem("firstLoadDone") === null) {
      setTimeout(() => {
        window.sessionStorage.setItem("firstLoadDone", 1);
        setAnimate(false);
      }, 7500);
    } else {
      setAnimate(false)
    }
  });

  return (
    <>
      {animate ? <Entry /> : <Home launches={hardcodeLaunches.result} />}
    </>
  );
}

export default App;



